apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orchestrator-service
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: orchestrator-service-config
    creationPolicy: Owner
  dataFrom:
    - extract: { key: app/ecommerce }
    - extract: { key: app/orchestrator-service }
