mode: standalone
auth:
  rootUser: minioadmin
  rootPassword: minioadmin
defaultBuckets: "products,avatars"
persistence:
  size: 4Gi
resources:
  requests: { cpu: 50m, memory: 256Mi }
  limits:   { cpu: 500m, memory: 512Mi }
