apiVersion: v1
kind: Service
metadata:
  name: mock-paypal-service
  namespace: apps
  labels: { app: mock-paypal-service }
spec:
  type: ClusterIP
  selector: { app: mock-paypal-service }
  ports:
    - { name: http, port: 8585, targetPort: http }
    - { name: management, port: 18585, targetPort: management }
