apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: apps
  labels: { app: payment-service }
spec:
  type: ClusterIP
  selector: { app: payment-service }
  ports:
    - { name: http, port: 8484, targetPort: http }
    - { name: management, port: 18484, targetPort: management }
