apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: apps
  labels: { app: order-service }
spec:
  replicas: 1
  selector:
    matchLabels: { app: order-service }
  template:
    metadata:
      labels: { app: order-service }
    spec:
      containers:
        - name: order-service
          image: localhost:5001/order-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - { name: http, containerPort: 9696 }
            - { name: management, containerPort: 19696 }
          env:
            - { name: VAULT_TOKEN, value: root }
            - { name: SPRING_CLOUD_VAULT_URI, value: http://vault.infra.svc.cluster.local:8200 }
            - { name: JAVA_OPTS, value: "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC" }
          resources:
            requests: { cpu: 100m, memory: 384Mi }
            limits:   { cpu: 1000m, memory: 512Mi }
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: management }
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 4
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: management }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
