apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: apps
  labels: { app: product-service }
spec:
  type: ClusterIP
  selector: { app: product-service }
  ports:
    - { name: http, port: 7777, targetPort: http }
    - { name: management, port: 17777, targetPort: management }
