apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: apps
  labels: { app: bff-service }
spec:
  type: ClusterIP
  selector: { app: bff-service }
  ports:
    - { name: http, port: 8087, targetPort: http }
    - { name: management, port: 18087, targetPort: management }
