spring:
  application:
    name: bff-service
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN}
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: ecommerce
        application-name: bff-service
  config:
    import: optional:vault://
server:
  servlet:
    context-path: /bff-service
management:
  server:
    port: 18087
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  metrics:
    tags:
      application: ${spring.application.name}
