apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: apps
  labels: { app: gateway }
spec:
  replicas: 1
  selector:
    matchLabels: { app: gateway }
  template:
    metadata:
      labels: { app: gateway }
    spec:
      containers:
        - name: gateway
          image: localhost:5001/gateway:dev
          imagePullPolicy: IfNotPresent
          ports:
            - { name: http, containerPort: 6868 }
            - { name: management, containerPort: 19093 }
          env:
            - { name: VAULT_TOKEN, value: root }
            - { name: SPRING_CLOUD_VAULT_URI, value: http://vault.infra.svc.cluster.local:8200 }
            - { name: JAVA_OPTS, value: "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC" }
          resources:
            requests: { cpu: 200m, memory: 512Mi }
            limits:   { cpu: 1500m, memory: 768Mi }
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: management }
            initialDelaySeconds: 45
            periodSeconds: 15
            failureThreshold: 4
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: management }
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 6
