spring:
  application:
    name: authorization-server
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN}
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: ecommerce
        application-name: authorization-server
        additional-contexts: core-s3
  config:
    import: "vault://secret/ecommerce,vault://secret/authorization-server,vault://secret/core-s3"
  mail:
    username: ${APPLICATION_MAIL_USERNAME}
    password: ${APPLICATION_MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
server:
  servlet:
    context-path: /authorization-server
management:
  server:
    port: 19091
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db,redis,mail
  metrics:
    tags:
      application: ${spring.application.name}