apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: apps
  labels: { app: inventory-service }
spec:
  type: ClusterIP
  selector: { app: inventory-service }
  ports:
    - { name: http, port: 6969, targetPort: http }
    - { name: grpc, port: 9090, targetPort: grpc }
    - { name: management, port: 16969, targetPort: management }
