apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: order-service
          volumeMounts:
            - { name: app-config, mountPath: /etc/app-config, readOnly: true }
      volumes:
        - name: app-config
          secret:
            secretName: order-service-config
