apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../../base/authorization-server
  - ../../base/gateway
  - ../../base/product-service
  - ../../base/inventory-service
  - ../../base/order-service
  - ../../base/payment-service
  - ../../base/orchestrator-service
  - ../../base/bff-service
