apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../../base/authorization-server
  - ../../base/gateway
  - ../../base/product-service
  - ../../base/inventory-service
  - ../../base/order-service
  - ../../base/payment-service
  - ../../base/orchestrator-service
  - ../../base/bff-service
  - ../../base/mock-paypal-service
  - ../../base/frontend
patches:
  - target:
      kind: Deployment
      name: payment-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRING_APPLICATION_JSON
          value: '{"application":{"paypal":{"base-url":"http://mock-paypal-service.apps.svc.cluster.local:8585/mock-paypal-service"}}}'
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PAYPAL_TUNNEL_URL
          value: "http://api.microecom.local"
