apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bootstrap
resources:
  - job.yaml
configMapGenerator:
  - name: vault-seed-scripts
    files:
      - seed.sh
generatorOptions:
  disableNameSuffixHash: true
