apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bootstrap
resources:
  - job.yaml
configMapGenerator:
  - name: mysql-seed-scripts
    files:
      - seed.sh
  - name: mysql-seed-sql
    files:
      - ../../../../docker/ecommerce.sql
generatorOptions:
  disableNameSuffixHash: true
